/**
 * Created by Praveen on 11/09/2015.
 */

export const ADD_DEVICE = "ADD_DEVICE";

export const REMOVE_DEVICE = "REMOVE_DEVICE";

export const ADD_DEVICE_ATTRIBUTES = "ADD_DEVICE_ATTRIBUTES";

export const REMOVE_DEVICE_WITH_ATTRIBUTES = "REMOVE_DEVICE_WITH_ATTRIBUTES";

export const SELECT_DEVICE = "SELECT_DEVICE";

export const DESELECT_DEVICE = "DESELECT_DEVICE";

export const SET_DETAIL_VIEW_FOR_DEVICE = "SET_DETAIL_VIEW_FOR_DEVICE";

export const REMOVE_DETAIL_VIEW_FOR_DEVICE = "REMOVE_DETAIL_VIEW_FOR_DEVICE";

export const ADD_NOTIFICATION = "ADD_NOTIFICATION";

export const REMOVE_NOTIFICATION = "REMOVE_NOTIFICATION";

export const SELECT_NAVIGATION_ITEM = "SELECT_NAVIGATION_ITEM";

export const ADD_FILE = "ADD_FILE";

export const SELECT_FILE = "SELECT_FILE";

export const DESELECT_FILE = "DESELECT_FILE";