/**
 * Created by Praveen on 11/09/2015.
 */

export const ADD_DEVICE = "ADD_DEVICE";

export const REMOVE_DEVICE = "REMOVE_DEVICE";

export const ADD_DEVICE_ATTRIBUTES = "ADD_DEVICE_ATTRIBUTES";

export const SELECT_DEVICE = "SELECT_DEVICE";

export const DESELECT_DEVICE = "DESELECT_DEVICE";

export const SET_DETAIL_VIEW_FOR_DEVICE = "SET_DETAIL_VIEW_FOR_DEVICE";

export const REMOVE_DETAIL_VIEW_FOR_DEVICE = "REMOVE_DETAIL_VIEW_FOR_DEVICE";